authors:
  brettchabot:
    name: "Brett Chabot"
    description: "Maintainer"
    avatar: "https://avatars.githubusercontent.com/u/4038919?v=4"
    url: "https://github.com/brettchabot"
  hoisie:
    name: "Michael Hoisie"
    description: "Maintainer"
    avatar: "https://avatars.githubusercontent.com/u/125547?v=4"
    url: "https://github.com/hoisie"
  jongerrish:
    name: "Jonathan Gerrish"
    description: "Maintainer"
    avatar: "https://avatars.githubusercontent.com/u/6314616?v=4"
    url: "https://github.com/jongerrish"
  Umesh-01:
    name: "Umesh Singh"
    description: "Contributor"
    avatar: "https://avatars.githubusercontent.com/u/83420185?v=4"
    url: "https://github.com/Umesh-01"
  utzcoz:
    name: "utzcoz"
    description: "Maintainer"
    avatar: "https://avatars.githubusercontent.com/u/43091780?v=4"
    url: "https://github.com/utzcoz"
  xian:
    name: "Christian Williams"
    description: "Maintainer"
    avatar: "https://avatars.githubusercontent.com/u/40298?v=4"
    url: "https://github.com/xian"
